/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.mf.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "provincia"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="provincia", catalog="comuni" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ProvinciaEntity.countAll", query="SELECT COUNT(x) FROM ProvinciaEntity x" )
} )
public class ProvinciaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="provincia_id", nullable=false)
    private Integer    provinciaId  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nome", length=80)
    private String     nome         ;

    @Column(name="sigla", length=5)
    private String     sigla        ;

    @Column(name="capoluogo")
    private Integer    capoluogo    ;

	// "regioneId" (column "regione_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="regione_id", referencedColumnName="regione_id")
    private RegioneEntity regione     ;

    @OneToMany(mappedBy="provincia", targetEntity=ComuneEntity.class)
    private List<ComuneEntity> listOfComune;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ProvinciaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setProvinciaId( Integer provinciaId ) {
        this.provinciaId = provinciaId ;
    }
    public Integer getProvinciaId() {
        return this.provinciaId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nome ( VARCHAR ) 
    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }

    //--- DATABASE MAPPING : sigla ( VARCHAR ) 
    public void setSigla( String sigla ) {
        this.sigla = sigla;
    }
    public String getSigla() {
        return this.sigla;
    }

    //--- DATABASE MAPPING : capoluogo ( INT ) 
    public void setCapoluogo( Integer capoluogo ) {
        this.capoluogo = capoluogo;
    }
    public Integer getCapoluogo() {
        return this.capoluogo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setRegione( RegioneEntity regione ) {
        this.regione = regione;
    }
    public RegioneEntity getRegione() {
        return this.regione;
    }

    public void setListOfComune( List<ComuneEntity> listOfComune ) {
        this.listOfComune = listOfComune;
    }
    public List<ComuneEntity> getListOfComune() {
        return this.listOfComune;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(provinciaId);
        sb.append("]:"); 
        sb.append(nome);
        sb.append("|");
        sb.append(sigla);
        sb.append("|");
        sb.append(capoluogo);
        return sb.toString(); 
    } 

}
