
/*
 * Created on 29 ago 2016 ( Time 11:04:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.mock;

import java.util.LinkedList;
import java.util.List;

import org.mf.bean.Comune;
import org.mf.test.MockValues;

public class ComuneMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Comune createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}

	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Comune createInstance( Integer comuneId ) {
		Comune comune = createNewInstance();
		// Init Primary Key fields
		comune.setComuneId( comuneId) ;
		return comune;
	}

	/**
	 * Creates an instance without Primary Key
	 * @param id1
	 * @return
	 */
	public Comune createNewInstance() {
		Comune comune = new Comune();
		// Init Data fields
		comune.setNome( mockValues.nextString(80) ) ; // java.lang.String 
		comune.setCodicecatastale( mockValues.nextString(4) ) ; // java.lang.String 
		comune.setAbitanti( mockValues.nextInteger() ) ; // java.lang.Integer 
		comune.setCapoluogo( mockValues.nextBoolean() ) ; // java.lang.Boolean 
		// Init Link fields (if any)
		// setProvincia( TODO ) ; // Provincia 
		return comune;
	}

	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Comune> createList(int count) {
		List<Comune> list = new LinkedList<Comune>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
