
/*
 * Created on 5 ago 2016 ( Time 15:52:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.mock;

import java.util.LinkedList;
import java.util.List;

import org.mf.bean.jpa.ProvinciaEntity;
import org.mf.test.MockValues;

public class ProvinciaEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ProvinciaEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}

	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ProvinciaEntity createInstance( Integer provinciaId ) {
		ProvinciaEntity entity = createNewInstance();
		// Init Primary Key fields
		entity.setProvinciaId( provinciaId) ;
		return entity ;
	}

	/**
	 * Creates an instance without Primary Key
	 * @param id1
	 * @return
	 */
	public ProvinciaEntity createNewInstance() {
		ProvinciaEntity entity = new ProvinciaEntity();
		// Init Data fields
		entity.setNome( mockValues.nextString(80) ) ; // java.lang.String 
		entity.setSigla( mockValues.nextString(5) ) ; // java.lang.String 
		entity.setCapoluogo( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setRegione( TODO ) ; // Regione 
		// setListOfComune( TODO ) ; // List<Comune> 
		return entity ;
	}

	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ProvinciaEntity> createList(int count) {
		List<ProvinciaEntity> list = new LinkedList<ProvinciaEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
