
/*
 * Created on 29 ago 2016 ( Time 11:04:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.mock;

import java.util.LinkedList;
import java.util.List;

import org.mf.bean.Provincia;
import org.mf.test.MockValues;

public class ProvinciaMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Provincia createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}

	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Provincia createInstance( Integer provinciaId ) {
		Provincia provincia = createNewInstance();
		// Init Primary Key fields
		provincia.setProvinciaId( provinciaId) ;
		return provincia;
	}

	/**
	 * Creates an instance without Primary Key
	 * @param id1
	 * @return
	 */
	public Provincia createNewInstance() {
		Provincia provincia = new Provincia();
		// Init Data fields
		provincia.setNome( mockValues.nextString(80) ) ; // java.lang.String 
		provincia.setSigla( mockValues.nextString(5) ) ; // java.lang.String 
		provincia.setCapoluogo( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setRegione( TODO ) ; // Regione 
		// setListOfComune( TODO ) ; // List<Comune> 
		return provincia;
	}

	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Provincia> createList(int count) {
		List<Provincia> list = new LinkedList<Provincia>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
