
/*
 * Created on 5 ago 2016 ( Time 15:52:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.mock;

import java.util.LinkedList;
import java.util.List;

import org.mf.bean.jpa.RegioneEntity;
import org.mf.test.MockValues;

public class RegioneEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public RegioneEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}

	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public RegioneEntity createInstance( Integer regioneId ) {
		RegioneEntity entity = createNewInstance();
		// Init Primary Key fields
		entity.setRegioneId( regioneId) ;
		return entity ;
	}

	/**
	 * Creates an instance without Primary Key
	 * @param id1
	 * @return
	 */
	public RegioneEntity createNewInstance() {
		RegioneEntity entity = new RegioneEntity();
		// Init Data fields
		entity.setNome( mockValues.nextString(80) ) ; // java.lang.String 
		entity.setNose( mockValues.nextString(15) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfProvincia( TODO ) ; // List<Provincia> 
		return entity ;
	}

	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<RegioneEntity> createList(int count) {
		List<RegioneEntity> list = new LinkedList<RegioneEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
