/*
 * Created on 1 ago 2016 ( Time 13:27:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.web.listitem;

import org.mf.bean.Comune;
import org.mf.web.common.ListItem;

public class ComuneListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ComuneListItem(Comune comune) {
		super();

		this.value = ""
			 + (comune != null ? comune.getComuneId() : "")
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = (comune != null ? comune.toString() : "--");
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
