/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.web.listitem;

import org.mf.bean.Provincia;
import org.mf.web.common.ListItem;

public class ProvinciaListItem implements ListItem {

	private final String value ;
	private final String label ;
	private final int regioneId;
	
	public ProvinciaListItem(Provincia provincia) {
		super();
		this.value = "" + (provincia != null ? provincia.getProvinciaId() : "");
		this.label = provincia != null ? provincia.getNome() : "--";
		this.regioneId = provincia != null ? provincia.getRegioneId() : 0;
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}
	
	public int getRegioneId() {
		return regioneId;
	}

}
