/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.web.listitem;

import org.mf.bean.Regione;
import org.mf.web.common.ListItem;

public class RegioneListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public RegioneListItem(Regione regione) {
		super();

		this.value = ""
			 + (regione != null ? regione.getRegioneId() : "")
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = (regione != null ? regione.toString() : "--");
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
