/*
 * Created on 5 ago 2016 ( Time 15:52:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.mf.bean.Provincia;
import org.mf.bean.jpa.ProvinciaEntity;
import org.mf.bean.jpa.RegioneEntity;
import org.mf.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ProvinciaServiceMapperTest {

	private ProvinciaServiceMapper provinciaServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		provinciaServiceMapper = new ProvinciaServiceMapper();
		provinciaServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ProvinciaEntity' to 'Provincia'
	 * @param provinciaEntity
	 */
	@Test
	public void testMapProvinciaEntityToProvincia() {
		// Given
		ProvinciaEntity provinciaEntity = new ProvinciaEntity();
		provinciaEntity.setNome(mockValues.nextString(80));
		provinciaEntity.setSigla(mockValues.nextString(5));
		provinciaEntity.setCapoluogo(mockValues.nextInteger());
		provinciaEntity.setRegione(new RegioneEntity());
		provinciaEntity.getRegione().setRegioneId(mockValues.nextInteger());
		
		// When
		Provincia provincia = provinciaServiceMapper.mapProvinciaEntityToProvincia(provinciaEntity);
		
		// Then
		assertEquals(provinciaEntity.getNome(), provincia.getNome());
		assertEquals(provinciaEntity.getSigla(), provincia.getSigla());
		assertEquals(provinciaEntity.getCapoluogo(), provincia.getCapoluogo());
		assertEquals(provinciaEntity.getRegione().getRegioneId(), provincia.getRegioneId());
	}
	
	/**
	 * Test : Mapping from 'Provincia' to 'ProvinciaEntity'
	 */
	@Test
	public void testMapProvinciaToProvinciaEntity() {
		// Given
		Provincia provincia = new Provincia();
		provincia.setNome(mockValues.nextString(80));
		provincia.setSigla(mockValues.nextString(5));
		provincia.setCapoluogo(mockValues.nextInteger());
		provincia.setRegioneId(mockValues.nextInteger());

		ProvinciaEntity provinciaEntity = new ProvinciaEntity();
		
		// When
		provinciaServiceMapper.mapProvinciaToProvinciaEntity(provincia, provinciaEntity);
		
		// Then
		assertEquals(provincia.getNome(), provinciaEntity.getNome());
		assertEquals(provincia.getSigla(), provinciaEntity.getSigla());
		assertEquals(provincia.getCapoluogo(), provinciaEntity.getCapoluogo());
		assertEquals(provincia.getRegioneId(), provinciaEntity.getRegione().getRegioneId());
	}

}