/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.business.service;

import java.util.List;

import org.mf.bean.Provincia;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity Provincia.
 */
public interface ProvinciaService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param provinciaId
	 * @return entity
	 */
	Provincia findById(Integer provinciaId) ;

	/**
	 * Load the page request.
	 * @return Page
	 */
	Page<Provincia> findAll(Pageable pageRequest);

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Provincia> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Provincia save(Provincia entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Provincia update(Provincia entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Provincia create(Provincia entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param provinciaId
	 */
	void delete(Integer provinciaId);
}
