/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.business.service;

import java.util.List;

import org.mf.bean.Regione;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity Regione.
 */
public interface RegioneService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param regioneId
	 * @return entity
	 */
	Regione findById(Integer regioneId) ;

	/**
	 * Load the page request.
	 * @return Page
	 */
	Page<Regione> findAll(Pageable pageRequest);

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Regione> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Regione save(Regione entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Regione update(Regione entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Regione create(Regione entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param regioneId
	 */
	void delete(Integer regioneId);
}
