/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.mf.web.common.AbstractController;
import org.mf.web.common.FormMode;
import org.mf.web.common.Message;
import org.mf.web.common.MessageType;

//--- Entities
import org.mf.bean.Provincia;
import org.mf.bean.Regione;

//--- Services 
import org.mf.business.service.ProvinciaService;
import org.mf.business.service.RegioneService;

//--- List Items 
import org.mf.web.listitem.RegioneListItem;

/**
 * Spring MVC controller for 'Provincia' management.
 */
@Controller
@RequestMapping("/provincia")
public class ProvinciaController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "provincia";
	private static final String MAIN_LIST_NAME   = "list";
	private static final String MAIN_PAGE_NAME   = "page";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "provincia/form";
	private static final String JSP_LIST   = "provincia/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/provincia/create";
	private static final String SAVE_ACTION_UPDATE   = "/provincia/update";

	//--- Main entity service
	@Autowired
    private ProvinciaService provinciaService; // Injected by Spring
	//--- Other service(s)
	@Autowired
    private RegioneService regioneService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ProvinciaController() {
		super(ProvinciaController.class, MAIN_ENTITY_NAME );
		log("ProvinciaController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Regione"
	 * @param model
	 */
	private void populateListOfRegioneItems(Model model) {
		List<Regione> list = regioneService.findAll();
		List<RegioneListItem> items = new LinkedList<RegioneListItem>();
		if (list.isEmpty()) {
			items.add(new RegioneListItem( null ) );
		} else {
			for ( Regione regione : list ) {
				items.add(new RegioneListItem( regione ) );
			}
		}
		model.addAttribute("listOfRegioneItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param provincia
	 */
	private void populateModel(Model model, Provincia provincia, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, provincia);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfRegioneItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfRegioneItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Provincia found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Provincia> list = provinciaService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a page with the occurrences of Provincia found in the database
	 * @param pageable
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping(produces="text/html")
	public String list(Pageable pageable, Model model) {
		log("Action 'list'");
		Page<Provincia> page = provinciaService.findAll(pageable);
	    model.addAttribute(MAIN_PAGE_NAME, page);
	    int nrOfPages = page.getTotalPages();
	    model.addAttribute("maxPages", nrOfPages);
	    return JSP_LIST;
	}	

	/**
	 * Shows a form page in order to create a new Provincia
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Provincia provincia = new Provincia();	
		populateModel( model, provincia, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Provincia
	 * @param model Spring MVC model
	 * @param provinciaId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{provinciaId}")
	public String formForUpdate(Model model, @PathVariable("provinciaId") Integer provinciaId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Provincia provincia = provinciaService.findById(provinciaId);
		populateModel( model, provincia, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param provincia  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Provincia provincia, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Provincia provinciaCreated = provinciaService.create(provincia); 
				model.addAttribute(MAIN_ENTITY_NAME, provinciaCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));

				return redirectToForm(httpServletRequest, provinciaCreated.getProvinciaId() );
			} else {
				populateModel( model, provincia, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "provincia.error.create", e);
			populateModel( model, provincia, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param provincia  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Provincia provincia, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Provincia provinciaSaved = provinciaService.update(provincia);
				model.addAttribute(MAIN_ENTITY_NAME, provinciaSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, provinciaSaved.getProvinciaId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, provincia, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "provincia.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, provincia, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param provinciaId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{provinciaId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("provinciaId") Integer provinciaId) {
		log("Action 'delete'" );
		try {
			provinciaService.delete( provinciaId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "provincia.error.delete", e);
		}
		return redirectToList();
	}

}
