/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.web.controller;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.mf.web.common.AbstractController;
import org.mf.web.common.FormMode;
import org.mf.web.common.Message;
import org.mf.web.common.MessageType;

//--- Entities
import org.mf.bean.Regione;

//--- Services 
import org.mf.business.service.RegioneService;


/**
 * Spring MVC controller for 'Regione' management.
 */
@Controller
@RequestMapping("/regione")
public class RegioneController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "regione";
	private static final String MAIN_LIST_NAME   = "list";
	private static final String MAIN_PAGE_NAME   = "page";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "regione/form";
	private static final String JSP_LIST   = "regione/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/regione/create";
	private static final String SAVE_ACTION_UPDATE   = "/regione/update";

	//--- Main entity service
	@Autowired
    private RegioneService regioneService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public RegioneController() {
		super(RegioneController.class, MAIN_ENTITY_NAME );
		log("RegioneController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param regione
	 */
	private void populateModel(Model model, Regione regione, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, regione);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Regione found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Regione> list = regioneService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a page with the occurrences of Regione found in the database
	 * @param pageable
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping(produces="text/html")
	public String list(Pageable pageable, Model model) {
		log("Action 'list'");
		Page<Regione> page = regioneService.findAll(pageable);
	    model.addAttribute(MAIN_PAGE_NAME, page);
	    int nrOfPages = page.getTotalPages();
	    model.addAttribute("maxPages", nrOfPages);
	    return JSP_LIST;
	}	

	/**
	 * Shows a form page in order to create a new Regione
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Regione regione = new Regione();	
		populateModel( model, regione, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Regione
	 * @param model Spring MVC model
	 * @param regioneId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{regioneId}")
	public String formForUpdate(Model model, @PathVariable("regioneId") Integer regioneId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Regione regione = regioneService.findById(regioneId);
		populateModel( model, regione, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param regione  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Regione regione, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Regione regioneCreated = regioneService.create(regione); 
				model.addAttribute(MAIN_ENTITY_NAME, regioneCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));

				return redirectToForm(httpServletRequest, regioneCreated.getRegioneId() );
			} else {
				populateModel( model, regione, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "regione.error.create", e);
			populateModel( model, regione, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param regione  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Regione regione, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Regione regioneSaved = regioneService.update(regione);
				model.addAttribute(MAIN_ENTITY_NAME, regioneSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, regioneSaved.getRegioneId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, regione, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "regione.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, regione, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param regioneId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{regioneId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("regioneId") Integer regioneId) {
		log("Action 'delete'" );
		try {
			regioneService.delete( regioneId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "regione.error.delete", e);
		}
		return redirectToList();
	}

}
