/*
 * Created on 5 ago 2016 ( Time 15:52:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.test.persistence;

import org.mf.bean.jpa.ComuneEntity;
import org.mf.configuration.ConfigurationTest;
import org.mf.configuration.JPAConfTest;
import org.mf.mock.ComuneEntityMock;
import org.mf.data.repository.jpa.ComuneJpaRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * JUnit test case for Comune persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { ConfigurationTest.class, JPAConfTest.class })
public class ComunePersistenceTest {

	@Autowired
	private ComuneJpaRepository service; 

	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
//		ComunePersistence service = PersistenceServiceProvider.getService(ComunePersistence.class);
		System.out.println("CountAll = " + service.count() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Comune persistence : delete + load ..." );
		
//		ComuneJpaRepository service = PersistenceServiceProvider.getService(ComuneJpaRepository.class);
		
		ComuneEntityMock mock = new ComuneEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 );
		// process( service, mock, ... );
	}

	private void process(ComuneJpaRepository service, ComuneEntityMock mock, Integer comuneId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		ComuneEntity entity = service.findOne( comuneId );
		if ( entity != null ) {
			// Found
			System.out.println("   FOUND : " + entity );

			// Save (update) with the same values to avoid database integrity errors
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found
			System.out.println("   NOT FOUND" );
			// Create a new instance
			entity = mock.createNewInstance();
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Provincia
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			System.out.println(" . delete : " );
			service.delete(entity.getComuneId());
			System.out.println("   deleted = " + entity);
			*/
		}		
	}
}
