/*
 * Created on 5 ago 2016 ( Time 15:52:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.test.persistence;

import org.mf.bean.jpa.ProvinciaEntity;
import org.mf.configuration.ConfigurationTest;
import org.mf.configuration.JPAConfTest;
import org.mf.mock.ProvinciaEntityMock;
import org.mf.data.repository.jpa.ProvinciaJpaRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * JUnit test case for Provincia persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { ConfigurationTest.class, JPAConfTest.class })
public class ProvinciaPersistenceTest {

	@Autowired
	private ProvinciaJpaRepository service; 

	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
//		ProvinciaPersistence service = PersistenceServiceProvider.getService(ProvinciaPersistence.class);
		System.out.println("CountAll = " + service.count() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Provincia persistence : delete + load ..." );
		
//		ProvinciaJpaRepository service = PersistenceServiceProvider.getService(ProvinciaJpaRepository.class);
		
		ProvinciaEntityMock mock = new ProvinciaEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 );
		// process( service, mock, ... );
	}

	private void process(ProvinciaJpaRepository service, ProvinciaEntityMock mock, Integer provinciaId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		ProvinciaEntity entity = service.findOne( provinciaId );
		if ( entity != null ) {
			// Found
			System.out.println("   FOUND : " + entity );

			// Save (update) with the same values to avoid database integrity errors
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found
			System.out.println("   NOT FOUND" );
			// Create a new instance
			entity = mock.createNewInstance();
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Regione
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			System.out.println(" . delete : " );
			service.delete(entity.getProvinciaId());
			System.out.println("   deleted = " + entity);
			*/
		}		
	}
}
