/*
 * Created on 1 ago 2016 ( Time 13:27:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;



public class Comune implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer comuneId;
    
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 80 )
    private String nome;

    @Size( max = 4 )
    private String codicecatastale;


    private Integer abitanti;


    private Boolean capoluogo;


    private Integer provinciaId;
    private String siglaProv;

	public Comune() {
	}
	
	public Comune(String nome, int abitanti, String codicecatastale, Provincia provincia, boolean capoLuogo) {
		super();
		int pos = nome.indexOf("/");
		if (pos >= 0)
			this.nome = nome.substring(0,pos);
		else
			this.nome = nome;
		this.abitanti = abitanti;
		this.codicecatastale = codicecatastale;
		this.provinciaId = provincia.getProvinciaId();
		this.capoluogo = capoLuogo;
	}
	
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setComuneId( Integer comuneId ) {
        this.comuneId = comuneId ;
    }

    public Integer getComuneId() {
        return this.comuneId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }
    public void setCodicecatastale( String codicecatastale ) {
        this.codicecatastale = codicecatastale;
    }
    public String getCodicecatastale() {
        return this.codicecatastale;
    }
    public void setAbitanti( Integer abitanti ) {
        this.abitanti = abitanti;
    }
    public Integer getAbitanti() {
        return this.abitanti;
    }
    public void setCapoluogo( Boolean capoluogo ) {
        this.capoluogo = capoluogo;
    }
    public Boolean getCapoluogo() {
        return this.capoluogo;
    }
    public void setProvinciaId( Integer provinciaId ) {
        this.provinciaId = provinciaId;
    }
    public Integer getProvinciaId() {
        return this.provinciaId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
//        sb.append(comuneId);
//        sb.append("|");
        sb.append(nome);
        if (siglaProv != null && !siglaProv.isEmpty()) {
	        sb.append(" (");
	        sb.append(siglaProv);
	        sb.append(")");
        }
//        sb.append("|");
//        sb.append(codicecatastale);
//        sb.append("|");
//        sb.append(abitanti);
//        sb.append("|");
//        sb.append(capoluogo);
//        sb.append("|");
//        sb.append(provinciaId);
        return sb.toString(); 
    }

	public void setSiglaProv(String siglaProv) {
		this.siglaProv = siglaProv;
	}

	public String getSiglaProv() {
		return siglaProv;
	}

}
