/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Provincia implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer provinciaId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 80 )
    private String nome;

    @Size( max = 5 )
    private String sigla;


    private Integer regioneId;


    private Integer capoluogo;


    public Provincia() {
    };

    public Provincia(String nome, String sigla, Regione regione) {
		this.nome = nome;
		this.sigla = sigla;
		this.regioneId = regione.getRegioneId();
	}

	//----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setProvinciaId( Integer provinciaId ) {
        this.provinciaId = provinciaId ;
    }

    public Integer getProvinciaId() {
        return this.provinciaId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }
    public void setSigla( String sigla ) {
        this.sigla = sigla;
    }
    public String getSigla() {
        return this.sigla;
    }
    public void setRegioneId( Integer regioneId ) {
        this.regioneId = regioneId;
    }
    public Integer getRegioneId() {
        return this.regioneId;
    }
    public void setCapoluogo( Integer capoluogo ) {
        this.capoluogo = capoluogo;
    }
    public Integer getCapoluogo() {
        return this.capoluogo;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
//        sb.append(provinciaId);
//        sb.append("|");
        sb.append(nome);
        sb.append(" (");
        sb.append(sigla);
        sb.append(")");
//        sb.append(regioneId);
//        sb.append("|");
//        sb.append(capoluogo);
        return sb.toString(); 
    } 

}
