/*
 * Created on 5 ago 2016 ( Time 15:52:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.mf.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import org.mf.enu.Nose;


public class Regione implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer regioneId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 80 )
    private String nome;

    @Size( max = 15 )
    private Nose nose;


    public Regione() {
    };

    public Regione(String nome, Nose nose) {
		this.nome = nome;
		this.nose = nose;
	}

	//----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRegioneId( Integer regioneId ) {
        this.regioneId = regioneId ;
    }

    public Integer getRegioneId() {
        return this.regioneId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }
    public void setNose( Nose nose ) {
        this.nose = nose;
    }
    public Nose getNose() {
        return this.nose;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
//        sb.append(regioneId);
//        sb.append("|");
        sb.append(nome);
//        sb.append("|");
//        sb.append(nose);
        return sb.toString(); 
    } 

}
